ALTER TABLE "Tenant"
ADD COLUMN IF NOT EXISTS "backup_policy_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "backup_frequency" TEXT NOT NULL DEFAULT 'DAILY',
ADD COLUMN IF NOT EXISTS "backup_retention_days" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN IF NOT EXISTS "vendor_mirror_enabled" BOOLEAN NOT NULL DEFAULT true;
